### ISSUE TITLE
dynamic idp redirector with OTP

### ISSUE THREAD

**Issue by louisgls** [thomasdarimont/keycloak-extension-playground#25]
Hello,

I have added the dynamic idp redirector extension, which is very great, but unfortunately, it seems that when I use a "conditional prompt OTP form" after the dynamic idp redirector, user is never prompt for OTP.
When I place the OTP before the idp, it works perfectly : user is prompt for OTP and then redirected to its IDP.
Am i doing something wrong ?
![image](https://user-images.githubusercontent.com/11679637/123457823-9b517a00-d5e4-11eb-88a3-d5c2d7c23d66.png)

**Comment by tomrutsaert** [comment]
I assume the IDP redirector, does a redirect to the IDP, and thus leaves the flow at that point.
If you want to do something after the redirect, you could add the conditional OTP form in the post broker login flow of that IDP.....

**Comment by louisgls** [comment]
> I assume the IDP redirector, does a redirect to the IDP, and thus leaves the flow at that point.
> If you want to do something after the redirect, you could add the conditional OTP form in the post broker login flow of that IDP.....

Solves the issue, thanks

**Comment by louisgls** [comment]
@tomrutsaert  : the problem of this workaround is that if we set the "CONFIGURE_OTP" for an user, user will not be prompted to configure his otp after authentication because the post login flow is forced...

**Comment by louisgls** [comment]
@tomrutsaert  I understand the solution to use the first broker login flow but what if the user isn't new and he just lost his otp configuration ?

**Comment by tomrutsaert** [comment]
in default keycloak otp is reset via password forgotten flow.
Otp form was not necessarily envisioned to be used in first or post broker login flow. Well, I do not know.
Anyway if there is no reset link in the conditional otp form, Than you might need to make your own otp form.....
I can not help you here
