### ISSUE TITLE
RememberMe isn't working

### ISSUE THREAD

**Issue by skathery1985** [thomasdarimont/keycloak-extension-playground#9]
Hi, first thank you for this great extensions, you saved time for us

the issue i found in "auth-identity-first-extension" is that remember me isn't working cuz it's in "SelectUserAuthinticatorform" class.

it should be in "PasswordAuthenticationForm" class in validatePasswordForm

String rememberMe = formData.getFirst("rememberMe");
        boolean remember = rememberMe != null && rememberMe.equalsIgnoreCase("on");
        if (remember) {
            context.getAuthenticationSession().setAuthNote(Details.REMEMBER_ME, "true");
            context.getEvent().detail(Details.REMEMBER_ME, "true");
        } else {
            context.getAuthenticationSession().removeAuthNote(Details.REMEMBER_ME);
        }

**Comment by thomasdarimont** [comment]
@skathery1985 thanks!
